import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "./layout/clientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"h-[100vh] overflow-y-auto"}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
